### ISSUE TITLE
Feature request: Adding sections to the head of a document

### ISSUE THREAD

**Issue by nkentNTIA** [limdauto/drf_openapi#106]
You might have already implemented this. but looking at the code and docs for both this package and django-rest-swagger, I can't tell if there Is an easy way to add sections to the head of the document, a la the `Errors` section in the [Docker Engine docs](https://docs.docker.com/engine/api/v1.25/#).

Am I missing something obvious, or is this something that can't currently be done?

**Comment by axnsan12** [comment]
If you look at the actual [swagger document](https://docs.docker.com/engine/api/v1.25/swagger.yaml) of that page you can see that the "sections" are just markdown headers in the API description.

The best point to add that would probably be in a [SchemaView override](https://github.com/limdauto/drf_openapi/blob/c0b773de649eae67c0c1014a836ec41047bfc862/drf_openapi/views.py#L17) by passing a description argument to [OpenApiSchemaGenerator](https://github.com/limdauto/drf_openapi/blob/c0b773de649eae67c0c1014a836ec41047bfc862/drf_openapi/entities.py#L86).

**Comment by nkentNTIA** [comment]
Ah, perfect! Thanks for getting back to me so fast! Works like a charm.
