### ISSUE TITLE
Validate response doesn't work with ReturnList

### ISSUE THREAD

**Issue by limdauto** [limdauto/drf_openapi#25]
I.e. specifying `many=True` in the serializer

**Comment by limdauto** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Validate response doesn't work with ReturnList](https://trello.com/c/18JaVpQn/3-validate-response-doesnt-work-with-returnlist)

**Comment by jathanism** [comment]
I think there are a couple other issues related to list-type serializers, too. There doesn't seem to be a way to get a naked array to render at all, which does feel related.

**Comment by limdauto** [comment]
Yay this is also fixed by: https://github.com/limdauto/drf_openapi/pull/55
