### ISSUE TITLE
List type doesn't render properly

### ISSUE THREAD

**Issue by limdauto** [limdauto/drf_openapi#28]

**Comment by limdauto** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [List type doesn't render properly](https://trello.com/c/rRAD6Jtr/2-list-type-doesnt-render-properly)

**Comment by limdauto** [comment]
This is a bug in DRF itself: https://github.com/encode/django-rest-framework/pull/5326

**Comment by tuffnatty** [comment]
@limdauto Still not good enough (. Arrays of booleans etc. now display correctly. But for `MySerializer(many=True)` fields, I get:
```json
{
    "items": {
        "type": "object"
    },
    "type": "array",
    "description": ""
}
```
What I want is:
```json
{
    "items": {
        "$ref": "#/definitions/MySerializer"
    },
    "type": "array",
    "description": ""
}
...
"definitions": {
    "MySerializer": {
        "properties": {
            "myfield1": {"type": "string", "description": "Dummy field description"},
            "myfield2": ...,
        }
    }
}
```

**Comment by limdauto** [comment]
Cool, thanks for testing it out. I will investigate. Probably related to https://github.com/limdauto/drf_openapi/issues/25

**Comment by limdauto** [comment]
@tuffnatty sorry for taking this long to resolve this. I have tried my best but supporting custom schema object type is going to require substantial refactor which I don't have time for right now. In the mean time, I will just return `object` as type of `items` along with its fields. Something like

<img width="562" alt="screen shot 2017-10-02 at 12 23 30 am" src="https://user-images.githubusercontent.com/2032984/31060291-03a59884-a709-11e7-9ab2-e4fd89370371.png">

I'm closing this ticket in favor of this one: https://github.com/limdauto/drf_openapi/issues/56 Let m know if you have any feedback
