### ISSUE TITLE
help_text is not shown for nested structures

### ISSUE THREAD

**Issue by avanov** [limdauto/drf_openapi#33]
When a schema node is a sub-schema, the help_text attributes of the sub-schema nodes is not shown in the generated docs.

**Comment by limdauto** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Help text isn't shown for nested structure](https://trello.com/c/Z0aKdPCJ/10-help-text-isnt-shown-for-nested-structure)

**Comment by limdauto** [comment]
Hmm I can't reproduce this Max. Not sure what we did last time but it showed up just fine for me.

<img width="557" alt="screen shot 2017-10-01 at 5 27 41 pm" src="https://user-images.githubusercontent.com/2032984/31056668-49d78f9c-a6cd-11e7-81cc-cbcc8f03d4f1.png">
