### ISSUE TITLE
Add to REST framework documentation.

### ISSUE THREAD

**Issue by tomchristie** [limdauto/drf_openapi#51]
This looks *awesome*! ✨

A pull request to add it to the [third party documentation packages](http://www.django-rest-framework.org/topics/documenting-your-api/#third-party-packages) would be a great idea. It should include a screenshot including the rather nice redoc theme.

You're welcome to list it as the first in that set of packages.

We probably also want a "Third party packages" section in our schema docs. - http://www.django-rest-framework.org/api-guide/schemas/

You could add this as an item there too, (tho use a shorter style without the screenshot there)

If you've not already done so it's also worth making sure to add it to the "REST framework" grid on the "django packages" site.

Nice work!!! 😎

**Comment by tomchristie** [comment]
As an aside... "CoreAPI is not compatible out of the box with OpenAPI" - Yup... I *do* want us to end up having feature parity there, so it *is* something that we'll work towards. (Eg. response schemas will be inbound in due course) Any input on the most important things you think we need to address would be most welcome!

**Comment by limdauto** [comment]
Oh wow, thanks Tom for your kind words. I will surely make a pull request to add this as a 3rd party tool for DRF when I get to an 1.0 release. There are a number of issues I want to iron out and stabilize the API, but hopefully with your endorsement more people will use this project and more feedbacks will come through.
