### ISSUE TITLE
When using /api/<version>/ as API_PREFIX the navigation sidebar only shows one entry

### ISSUE THREAD

**Issue by bikeshedder** [limdauto/drf_openapi#58]
* DRF OpenAPI version: 1.0 (pypi)
* Python version: 3.6
* Operating System: Fedora 26

### Description

I decided to use the URL schema `/api/<version>/<app>/<view_name>/`. Now the generated documentation does not list the apps in the navigation but only shows one entry called "API". When changing the schema to `/api-<version>/<app>/<view_name>/` it is picked up and the navigation is generated properly.

Question: Is it even a good idea to use the URL to generate the documentation. The actual app name would be more useful, wouln't it. At least it would get rid of this problem.

**Comment by bikeshedder** [comment]
I just realized that this also happens when using `rest_framework.documentation.include_docs_urls`. So I guess that one is caused by some code in DRF and is not drf_openapi specific.

**Comment by limdauto** [comment]
Thanks I'm gonna investigate. If I can fix it I will open a PR over at DRF.

**Comment by bikeshedder** [comment]
This is indeed an error of DRF and not of drf_openapi. After some consideration I switched to `API_PREFIX = '/v1.0/'` as it seems to be pretty much the standard nowadays. So I'm no longer affected by this issue. Still I find it odd that the first fragment of the path is used to build up the navigation and not the app label. I think using the app label (just like the Django Admin) would make a bit more sense.

**Comment by limdauto** [comment]
@bikeshedder actually I already noticed this and logged a ticket way earlier but it was deprioritized when I scrambled to get v1 out. I'm closing this since it's a duplication.

Duplicated of: https://github.com/limdauto/drf_openapi/issues/26
