### ISSUE TITLE
token authentication 

### ISSUE THREAD

**Issue by gfrancqu** [limdauto/drf_openapi#87]
* DRF OpenAPI version: 0.9.9 (from source, the latest the version number haven't been changed)
* Python version: 3.6
* Operating System:  linux

### Description

When using token authentication, the api endpoint cannot be rendered, all my endpoint are protected by an `IsAuthenticated` and  `TokenAuthentication` permissions. using sessions permissions it work well as soon as i am logged in (using swagger rendering) but I want to use token based authentication..

maybe is this an improvement to make ?

**Comment by fernandolins** [comment]
I had this same problem and I fixed it creating a custom permission like that:


#### custom_permission.py
```
from rest_framework import permissions


class IsAuthenticatedOrAPIDocsOnly(permissions.IsAuthenticated):
    def has_permission(self, request, view):
        if request._request.path == '/api/v1.0/docs/':
            return True

        return super(IsAuthenticatedOrAPIDocsOnly, self).has_permission(request, view)
```

#### settings.py
```
    ...
    'DEFAULT_PERMISSION_CLASSES': (
         'api.custom_permission.IsAuthenticatedOrAPIDocsOnly',
     ),
    ...
```

**Comment by werwty** [comment]
You could also subclass SchemaView and give that view its own permissions:

```
from rest_framework import response, permissions
from drf_openapi.views import SchemaView

class DocView(SchemaView):
    permission_classes = (permissions.AllowAny,)

urlpatterns.append(url(r'^api/(?P<version>(v1))/docs/',
                           DocView.as_view(title='API Docs'), name='api_schema'))

```

**Comment by fernandolins** [comment]
@werwty I did exactly what you said, but I kept having the same problem of the Doc API not being allowed to see some views.

I only solved it doing what I said above.

**Comment by werwty** [comment]
@fernandolins did you also pass `public=True` to `OpenApiSchemaGenerator.get_schema()`?

When I just set the permission class I was running into the same issue of drf_openapi only generating the schemas for views that I had permission to. I had to override the get() and make sure public=True was set before I could see all the schemas.

**Comment by gfrancqu** [comment]
thanks a lot @werwty ! it's working like a charm.
This method don't seems to be documented I think it should appear somewhere in the doc

i'm closing the issue

**Comment by fernandolins** [comment]
@werwty Oh, I didn't see that!
No, I didn't pass it.
I'll try it!
Thanks!
