### ISSUE TITLE
Release for DRF 3.7 Compatibility issues

### ISSUE THREAD

**Issue by ilmesi** [limdauto/drf_openapi#94]
* DRF OpenAPI version: 1.0.0
* Python version: 3.6+
* Operating System: OS X

### Description

Please upload a patch on Pypi with #77 included.

**Comment by alantrick** [comment]
So I was previously getting around this by using `pip3 install git+https://github.com/werwty/drf_openapi.git@drf3.7`, hoever, now pip is setfaulting while doing that...

**Comment by salexkidd** [comment]
@alantrick  We know that way. But it's not good way.

**Comment by werwty** [comment]
Hello, I recently requested (and was granted) contributor status to this repository. I've uploaded a new version of drf_openapi on PyPI: https://pypi.python.org/pypi/drf-openapi/1.0.1

I plan on going through and triaging open issues in the next couple of days.
Marking this issue as closed  :smiley:
