### ISSUE TITLE
Usage with GenericViewSet

### ISSUE THREAD

**Issue by Amoki** [limdauto/drf_openapi#96]
* DRF OpenAPI version: master
* Python version: 3.6
* Operating System: Linux

### Description

I use GenericViewSet do define my views, therefore I am not able to use decorators.
Is there a way to achieve that currently or it needs some implementation ?

**Comment by limdauto** [comment]
Can you post one of your views?

**Comment by Amoki** [comment]
```
class CloudViewSet(viewsets.ModelViewSet):
    serializer_class = CloudSerializer
    permission_classes = [permissions.IsAuthenticated, CloudPermission]

    def get_queryset(self):
        return self.request.user.cloud_set.all()
```

**Comment by Amoki** [comment]
Do you have any info or maybe clues to help me implementing this ?

**Comment by joeribekker** [comment]
You can overwrite the `dispatch` method and add decorate with the `view_config`:

```python
    @view_config(request_serializer=CloudSerializer, response_serializer=CloudSerializer)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

```

However, this will fail if your `serializer_class` attribute is referring to an instance of `VersionedSerializers`. If you point it to a regular DRF serializer it works.

**Comment by volodchenkov** [comment]
I use ModelViewSet too and register it in views.py by:
`
router = DefaultRouter(trailing_slash=True)

router.register('scenarios', views.Scenarios, 'scenarios')
`
drf-openapi do not see my views
